### ISSUE TITLE
register_datetime is updated for every features when a new feature is added

### ISSUE THREAD

**Issue by RousseauLambertLP** [ECCC-MSC/geomet-data-registry#19]
When we add a new feature to our tileindex, looks like all the features `register_datetime` is updated, not only the one matching the filename.

we need to fix the _update_by_query filter to only update `register_datetime` where the filename is exactly the same.

CC @tomkralidis @Dukestep

**Comment by Dukestep** [comment]
Seems like the JSON object passed by the `update_by_query` method does not contain the "query" key anymore. I'll take a look and fix this!

**Comment by Dukestep** [comment]
This should be fixed in #20 but I will take a look when we have more additions to the ES store. There doesn't seem to be any active AMQP feeds feeding ES. Once this is confirmed, I will close the issue.

**Comment by Dukestep** [comment]
Confirmed that this is fixed by the referenced MR. Closing.
