### ISSUE TITLE
Let ES handle and assign _id

### ISSUE THREAD

**Issue by RousseauLambertLP** [ECCC-MSC/geomet-data-registry#46]
According to ES documentation, the process to insert new entries in ES might be faster if let ES assign the _id field by itself instead of assigning it ourself.

I don't see any impact of letting ES create the _id, any thoughts @tomkralidis and @Dukestep ?

**Comment by Dukestep** [comment]
Documentation for reference:

https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-indexing-speed.html#_use_auto_generated_ids

I agree that this would be a good idea. We could allow ES to auto-generate the `_id`. We already store the identifier in `properties.identifier` of the index document.

**Comment by tomkralidis** [comment]
Sure. Can we try and assess/compare performance?

**Comment by Dukestep** [comment]
Upon further investigating and during LP's work on bulk inserts, we discovered that we cannot auto-generate IDs given that we rely on this IDs when updating documents. A predictable is then necessary for us to update an existing record.
 
See: https://discuss.elastic.co/t/using-custom-value-for--id-instead-of-es-generated-value/96540/2

> Elasticsearch autogenerated ids are faster to index since Elasticsearch can safely assume that the generated ids do not exist in the index yet. However this usually makes sense only for append-only data such as log lines. In your case I suspect you will occasionally need to replace or update some documents, so predictable ids will make it easier.

Looks like we'll need to stick to generating IDs. Well get our performance boost from the ingest pipeline and bulk loading anyways.

Closing for now.
