### ISSUE TITLE
All datetimes should contain Zulu designator 'Z'

### ISSUE THREAD

**Issue by Dukestep** [ECCC-MSC/geomet-data-registry#49]
Currently, an indexed document looks like this

```
    "properties": {
      "elevation": "2m",
      "identifier": "GDPS.ETA_TT-20190701000000-20190701000000",
      "reference_datetime": "2019-07-01T00:00:00",
      "file_creation_datetime": "2019-07-01T03:46:46.100000",
      "filepath": "/data-san/geomet/dev/feeds/model_gem_global/25km/grib2/lat_lon/00/000/CMC_glb_TMP_TGL_2_latlon.24x.24_2019070100_P000.grib2",
      "forecast_hour_datetime": "2019-07-01T00:00:00",
      "member": null,
      "identify_datetime": "2019-09-27T18:55:51.066768",
      "receive_datetime": "2019-09-27T18:55:50.893790",
      "layer": "GDPS.ETA_TT",
      "register_datetime": "2019-09-27T18:55:51.067903"
    }
```

I suggest that all datetimes for each layer handler (i.e `forecast_hour_datetime`, `reference_datetime`, `file_creation_datetime`, `identify_datetime`, etc...) should contain the Zulu designator (`Z`).

For ElasticSearch, this will allow us to more strictly define the format expected in the ES mapping. For example:

```
                    'reference_datetime': {
                        'type': 'date',
                        'format': 'date_time_no_millis'
                    },
                    'file_creation_datetime': {
                        'type': 'date',
                        'format': 'date_time'
                    },
```

Unfortunately, datetime does not seem to support this out of the box and the only solution I've found is to `isoformat() + 'Z'`. I don't find this very desirable. @tomkralidis, any other options?

**Comment by tomkralidis** [comment]
We can create a utility function in `geomet_data_registry.util` like:

```python
from datetime import datetime
import pytz

def get_today_and_now():
   return pytz.utc.localize(datetime.utcnow())
```
```python
>>> tan = today_and_now()
>>> tan
datetime.datetime(2019, 9, 27, 20, 6, 25, 237504, tzinfo=<UTC>)
>>> utc_now.isoformat()
'2019-09-27T20:06:25.237504+00:00'
```
This will then provide a timezone aware datetime object.  Example:
`datetime.datetime(2019, 9, 27, 20, 6, 25, 237504, tzinfo=<UTC>`

Note that `Z` and `+00:00` are equivalent representations.

**Comment by Dukestep** [comment]
+1 for a function in `geomet_data_registry.util` but I'm pretty sure we'll want to keep the Z representation to avoid issues in MapServer? See https://mapserver.org/ogc/wms_time.html#time-patterns.
