### ISSUE TITLE
add URL property to handling workflow

### ISSUE THREAD

**Issue by RousseauLambertLP** [ECCC-MSC/geomet-data-registry#84]
Giving we are thinking of downloading on-the-fly data when we get a GetMap or GetFeatureInfo, we should add a property in ES mapping for the source data. 

For example, this source data could be the https path to a particular file on datamart.

This information (I think) could come from the amqp notification we get, something like `parent.msg.baseurl`. This could then be passed to the handler as a variable and written to ES for a feature.

The befit here is that we would only need to modify general files, like the layer base.py and the handler. And if the source changes, it will automatically be updated because it's directly from the amqp notifications.

We could call that property `source_path` ? Other ideas ?

cc @tomkralidis @Dukestep

**Comment by tomkralidis** [comment]
Update: given we are not opening/inspecting any incoming files, combined with the number of files downloaded to disk, it makes sense for us to (in downstream applications) only download/cache files as requested from APIs to reduce traffic.

Steps:
- add a `url` field in GDR's tileindex model
- decide which sarra feeds we will keep downloading data for or not
- for datasets which do not need to be downloaded, enable `discard True` in sarra feeds

Downstream applications will have to check if GDR's tileindex `filepath` exists and decide to download accordingly.

**Comment by RousseauLambertLP** [comment]
This feature was added in https://github.com/ECCC-MSC/geomet-data-registry/pull/102

The url property is added from sarracenia logs (`parent.msg.url`) so when testing and adding the files via the command line tool, the url is set to `null`
